services:
  redis:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-redis
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - redis_data:/data
  searxng:
    build:
      context: .
      dockerfile: Dockerfile
    image: searxng-custom:local
    container_name: searxng
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SEARXNG_BASE_URL=http://searxng.hikamer.f5.si/
    depends_on:
      - redis
      - tor
      - flaresolverr
      - flaresolverr2
      - flaresolverr3
      - flaresolverr4
  tor:
    image: dperson/torproxy:latest
    container_name: searxng-tor
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: searxng-flaresolverr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
  flaresolverr2:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: searxng-flaresolverr2
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
  flaresolverr3:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: searxng-flaresolverr3
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
  flaresolverr4:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: searxng-flaresolverr4
    restart: unless-stopped
    environment:
      - LOG_LEVEL=error
volumes:
  redis_data:
